# Generated by Django 5.1.4 on 2025-01-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0003_task_prio_task_status_alter_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('user_story', 'User Story'), ('technical_task', 'Technical Task')], default='user story', max_length=30),
        ),
    ]
