# Generated by Django 5.1.4 on 2025-01-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0004_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('user_story', 'User Story'), ('technical_task', 'Technical Task')], default='user_story', max_length=30),
        ),
    ]
