# Generated by Django 5.1.4 on 2025-02-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0009_alter_contact_color_alter_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.DeleteModel(
            name='SubTask',
        ),
    ]
