# Generated by Django 5.1.4 on 2025-02-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0012_rename_asignt_to_task_asigned_to_alter_contact_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='asigned_to',
            new_name='assigned_to',
        ),
    ]
