# Generated by Django 5.1.4 on 2025-03-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0013_rename_asigned_to_task_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='checked',
            field=models.CharField(choices=[('checked', 'Checked'), ('unchecked', 'Unchecked')], default='unchecked', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'Todo'), ('progress', 'In progress'), ('await', 'Await feedback'), ('done', 'Done')], default='todo', max_length=30),
        ),
    ]
